### ISSUE TITLE
Few Typos 

### ISSUE THREAD

**Issue by therealssj** [alex-phillips/clouddrive-php#1]
Thank you for this awesome api! Saved me a lot of work!
I found two issues on as follows
File.php Line 42
. "tokens/{$this->email}.token"), true);
Should be
 ."{$this->config['tokens_directory']}{$this->email}.token"), true);

File.php line 128
        return $response;
Should be 
        return $response['data'];

**Comment by alex-phillips** [comment]
Hey, thanks for the feedback! You're welcome to open up a pull request.

Also, I'm currently rewriting this library as its currently incomplete. The new version is also going to use a SQLite3 cache, so requests don't need to be made for everything such as determining if a node exists, getting metadata, getting parent nodes, etc. Ultimately, it's going to match the functionality of my Ruby project (https://github.com/alex-phillips/clouddrive).

The new rewrite won't be missing anything though. It will still be able to be used as an SDK as well as a command line app.

**Comment by therealssj** [comment]
Could you possibly add chunked uploading in the new SDK?

**Comment by alex-phillips** [comment]
When you say chunked, do you mean multi-file or multi-part for a single file?

**Comment by therealssj** [comment]
Multi-part for single file.

**Comment by alex-phillips** [comment]
I know Amazon S3 supports that, but I don't see it supported in the CloudDrive API docs. Unless I'm missing it. If you can find where it's supported, I'd be happy to add it.

https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes

**Comment by therealssj** [comment]
aah! I thought you would know how to :P
I am still looking too :/
Dropped question on developer forum for same.

**Comment by therealssj** [comment]
Also there was this [question](https://forums.developer.amazon.com/forums/thread.jspa?messageID=14050&#14050) on forum and in the answer the guy said it is possible :o
Or Does he mean something else when he says chunked transfer encoding?

**Comment by alex-phillips** [comment]
Ah nice. It may just be a certain way to handle the HTTP request. I'll reply in the forum for more information and see if I can implement it as well. If you find any info, let me know and we'll get it rolled in.

**Comment by therealssj** [comment]
I contacted support and they said that resumable uploads are in works and will be live in a couple of weeks.
Will have to wait till then i guess, i checked the online interface and even that does not do chunked uploads and large files usually timeout.

**Comment by alex-phillips** [comment]
No problem.

As I mentioned earlier, I'm currently rewriting this codebase. I should have a fairly stable release this weekend if you want to test it out. Will push it up as a new branch (probably `refactor`).

It's going to be a lot more complete, and with the caching in place, a LOT less API calls will be necessary to perform uploads.

**Comment by therealssj** [comment]
Sure I would love to test it out!!

**Comment by alex-phillips** [comment]
Just curious, are you most interested in the library for the CLI or the SDK? Or both? (I'm building the CLI to be an easy-to-use management tool for interacting with CloudDrive. I.e., `clouddrive upload FOLDER` to upload content)

**Comment by therealssj** [comment]
I am more interested in the SDK as i am going to use it in a project. Though no problems with me as i can always modify the CLI to meet my needs as i am doing with the current version.

**Comment by alex-phillips** [comment]
Refactor is live! Let me know what you think.

**Comment by therealssj** [comment]
Checking it out now!
So far i really like it!
I see what you meant when you said building for cli , really easy now to operate it using the cli with all these commands available directly!

**Comment by alex-phillips** [comment]
That was the original reason I built the project, but figured I'd build it out so the SDK was easily developed upon too. Sorry for the lack of docs as of now, hopefully it's pretty self explanatory. Let me know if you have any questions.

Going to go ahead and close this issue, feel free to open others and PRs are always welcome!
