### ISSUE TITLE
Is the 'link' option not available anymore ?

### ISSUE THREAD

**Issue by Drezzler** [alex-phillips/clouddrive-php#13]
So , i just tried to use "link" option to share a file with a friend and found that the option is not available .

But its mentioned on the projects main page . May be I am missing something ?

**Comment by alex-phillips** [comment]
@Drezzler, the option is available, but it looks like it didn't make it into the 'composer' package. I'll push out an update (0.1.1) in the next 10 minutes or so.

**Comment by alex-phillips** [comment]
@Drezzler  `0.1.1` is live. Let me know if that doesn't solve your issue.

**Comment by Drezzler** [comment]
@alex-phillips - Thank you so much for such a fast reply , link option now appears in the list of available options, but now their is an error with the entire package , I am unable do to run any command that sends a request to clouddrive api .

The error i am getting is -

`PHP Notice:  Undefined variable: response in vendor/alex-phillips/clouddrive/src/CloudDrive/Account.php on line 166
PHP Catchable fatal error:  Argument 1 passed to Utility\ParameterBag::merge() must be of the type array, null given, called in vendor/alex-phillips/clouddrive/src/CloudDrive/Account.php on line 166 and defined in vendor/alex-phillips/utilities/src/Utility/ParameterBag.php on line 30`

I have updated the package via `php composer.phar update` and it did update fine as i now see 0.1.1 as the installed version.

**Comment by alex-phillips** [comment]
@Drezzler I can look into this further, but I'm pretty sure the issue is that I've made some changes in either the `config.json` file that's saved, the database schema, or both. I apologize, it's been a while since I've touched the PHP version of this code last.

My best suggestion (unless you want to wait for me to troubleshoot this, but not sure when I will get to it), is to remove the cache directory on your computer (probably `~/.cache/clouddrive-php`) and start from scratch here.

I apologize, I should have kept better changelogs of the formats I've changed. But if you start over and re-sync fresh, it should work no problem.

**Comment by Drezzler** [comment]
@alex-phillips - Tried deleting ~/.cache folder and re-authorozing the app , did not work , but something that should be corrected is (probably unrelated to current problem) , `/.cache/config.json` has sqlite db set as 'clouddrive_php' , but the actual db that is being create is named "email@example.com.db" .

I will try to find what the problem is with my setup and post back here .

Ones again , thanks a lot for being so pro-active at dealing with issues.

**Comment by alex-phillips** [comment]
@Drezzler hmm. I will investigate the issue tonight and will hopefully find the problem pretty quickly. As far as the database name goes, that is only for MySQL and Postgres. SQLite saves as the email name to allow multi user support. 

Thanks for being interested in the project! I'm glad others are finding it useful.

**Comment by Drezzler** [comment]
Ok , so i am not sure if what i did is actually not a hack but a fix , so please do look into this when you have sometime .

I replaced line 166 of `src/CloudDrive/Account.php`

Replaced this 

``` php
$this->token->merge($response['data']);
```

with 

``` php
if (!empty($response)) { 
     $this->token->merge($response['data']);
 }
```

And the issue seems to have resolved for now .
