### ISSUE TITLE
Could not authenticate

### ISSUE THREAD

**Issue by OskarStark** [alex-phillips/clouddrive-php#24]
This is the used URL:
![bildschirmfoto 2016-11-14 um 15 26 55](https://cloud.githubusercontent.com/assets/995707/20268308/dcfdc2ec-aa7e-11e6-9285-7694ab63141e.png)

Maybe this fixes: https://github.com/nikkiii/flysystem-acd/issues/7

**Comment by therealssj** [comment]
The `client_id` in the url seems to be missing. I guess that is what the issue.
Putting that in should resolve your issue.
Please close the issue if that fixes it.

**Comment by OskarStark** [comment]
HI @therealssj,

I am using the steps from the README: https://github.com/alex-phillips/clouddrive-php#setup
and this should I guess

**Comment by therealssj** [comment]
@OskarStark u need to create a security profile and from there you get the `CLIENT_ID` and `CLIENT_SECRET`
- Go [here](https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fdeveloper.amazon.com%2Fap_login.html&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=mas_dev_portal&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=mas_dev_portal2&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&language=en_US&openid.pape.max_auth_age=1) and sign up as a new customer. 
- After you have signed up, login to your developer account. You will be taken to the dashboard. On the top you will see `Apps and Services` click on that. 
- After you click on `Apps and Services` you will be taken to another page where below `Apps and Services` you will see more options. There click on `Security Profiles`.
- On the next page click `Create a New Security Profile`. 

After you are done creating a security profile you will get a `CLIENT_ID` and `CLIENT_SECRET` which you need to use with this script.

**Comment by alex-phillips** [comment]
@OskarStark I haven't updated the readme setup process yet, but if you pull the master branch I've adjusted the code so that you can use the CLI without your own security profile. It will hit a Google AppEngine endpoint I have and authorize you with my security profile.

For security purposes, I've open sourced the endpoint here: https://github.com/alex-phillips/clouddrive-endpoint

**Comment by OskarStark** [comment]
Hi @alex-phillips , thank you for your feedback!

I created a security profile and now I have a CLIENT_ID and a SECRET, but if i open the URL, this is my result:
![bildschirmfoto 2016-11-23 um 08 53 24](https://cloud.githubusercontent.com/assets/995707/20554149/54297f64-b15a-11e6-8ec3-a739f4a94a61.png)

I am using https://github.com/nikkiii/flysystem-acd and it requires already dev-master of your lib.
I will do `composer update` now.

**Comment by OskarStark** [comment]
Hi again,

i set clientid and secret both empty (after a composer update), and the output changes to:
![bildschirmfoto 2016-11-23 um 08 55 57](https://cloud.githubusercontent.com/assets/995707/20554231/c300ab6a-b15a-11e6-8c00-260ff5739af1.png)

I opened the url an authenticated my account with my amazon credentials ✅ 

But the response looks like this:
![bildschirmfoto 2016-11-23 um 08 57 23](https://cloud.githubusercontent.com/assets/995707/20554254/e297b5ea-b15a-11e6-8d4d-3257e88c6cea.png)
![bildschirmfoto 2016-11-23 um 08 57 26](https://cloud.githubusercontent.com/assets/995707/20554257/e6000c28-b15a-11e6-9d87-d80c02b18e89.png)

Is this correct?

**Comment by OskarStark** [comment]
The second time i did the login with my credentials i got something like this:

```
{"access_token":"FOO","refresh_token":"BAR","token_type":"bearer","expires_in":3598}
```

What shall i do with these response?

Thanks for helping me out! 👍

**Comment by therealssj** [comment]
@OskarStark IIRC after you authorize you are supposed to paste the output into the terminal so the cli can prolly save the `access_token` and the `refresh_token` in the sqlite database for future.
The `refresh_token` is crucial for the working of the cli.

**Comment by OskarStark** [comment]
Ok great, after pasting the json to the cli, it seems to work! 👍 

Thank you guys, but we should definitely work on the README/Setup instructions 😄
