### ISSUE TITLE
Ability to set scopes?

### ISSUE THREAD

**Issue by therealssj** [alex-phillips/clouddrive-php#3]
Instead of having a preset scope value would it not be better to set it using a variable so in future if there are any changes to scope values we can just update that variable and continue using the api.

P.S.
The scopes have already been updated and the current one set in the api does not work for new apps.
Here is the [page](https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started) with the new scopes.

**Comment by alex-phillips** [comment]
Great point. I'll get a change pushed out today to support this. Be on the lookout for a PR so I can get your feedback.

**Comment by alex-phillips** [comment]
@Mwesome See PR https://github.com/alex-phillips/clouddrive-php/pull/4
