### ISSUE TITLE
Download Files?

### ISSUE THREAD

**Issue by therealssj** [alex-phillips/clouddrive-php#6]
Are you planning to add file downloading in the future?

P.S
CloudDrive.php line 334 typo in exception output.

**Comment by alex-phillips** [comment]
@Mwesome See PR https://github.com/alex-phillips/clouddrive-php/pull/7

**Comment by alex-phillips** [comment]
Will go ahead and merge unless you have any feedback.

**Comment by alex-phillips** [comment]
Merged.

**Comment by therealssj** [comment]
Aah damn I keep missing out on all ur comments!
Will test and let you know the feedback soon!
