### ISSUE TITLE
File uploads with dots (`.`) in the name other than the extension

### ISSUE THREAD

**Issue by alex-phillips** [alex-phillips/clouddrive-php#9]
When uploading, any file with a 'dot' in the name other than the extension does not work properly. Note: This might be due to the dot in the filename or the directory it lives in. Will need some testing.

**Comment by therealssj** [comment]
Are u sure?
I have uploaded dozens of such files. 
Though I assumed they must be fine as the sizes were fine.
What issues did you see?

**Comment by alex-phillips** [comment]
It may not be files then but folders with a dot in the name. I went to upload a directory (both sub directories and files inside of those subdirectories had dots in the name) and all that was returned was a 400 response with no message. Need to test more, but my hunch is either the dot in the file or a dot in the actual folder name.

**Comment by alex-phillips** [comment]
@Mwesome Ran into a similar issue again. It may not be a 'naming' issue but rather a filetype issue.

**Comment by alex-phillips** [comment]
Opened a ticket with Amazon's support. This doesn't seem to be a filename issue with `.` but rather a file extension issue.
